/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visoes;

import controladores.HospitalController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author desenvolvedor2
 */
public class Hospital extends javax.swing.JFrame {

    private HospitalController controlador;

    /**
     * Creates new form Secretaria
     */
    public Hospital() {
        controlador = new HospitalController();
        initComponents();
        URL url = this.getClass().getResource("../imagens/hospital.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnMedicos = new javax.swing.JButton();
        btnEnfermeiros = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSalvar = new javax.swing.JMenuItem();
        menuImportar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital PLP");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hospital.png"))); // NOI18N
        jLabel1.setText("Hospital PLP");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnConsulta.setBackground(new java.awt.Color(51, 122, 183));
        btnConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultas.png"))); // NOI18N
        btnConsulta.setText("Consultas");
        btnConsulta.setToolTipText("Adicionar um novo paciente");
        btnConsulta.setBorder(null);
        btnConsulta.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btnConsulta.setMinimumSize(new java.awt.Dimension(103, 17));
        btnConsulta.setPreferredSize(new java.awt.Dimension(130, 35));
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        btnPacientes.setBackground(new java.awt.Color(51, 122, 183));
        btnPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/paciente.png"))); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.setToolTipText("Adicionar um novo paciente");
        btnPacientes.setBorder(null);
        btnPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPacientes.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btnPacientes.setMinimumSize(new java.awt.Dimension(103, 17));
        btnPacientes.setPreferredSize(new java.awt.Dimension(130, 35));
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });

        btnMedicos.setBackground(new java.awt.Color(51, 122, 183));
        btnMedicos.setForeground(new java.awt.Color(255, 255, 255));
        btnMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medico.png"))); // NOI18N
        btnMedicos.setText("Médicos");
        btnMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosActionPerformed(evt);
            }
        });

        btnEnfermeiros.setBackground(new java.awt.Color(51, 122, 183));
        btnEnfermeiros.setForeground(new java.awt.Color(255, 255, 255));
        btnEnfermeiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enfermeiro.png"))); // NOI18N
        btnEnfermeiros.setText("Enfermeiros");
        btnEnfermeiros.setToolTipText("Adicionar um novo paciente");
        btnEnfermeiros.setBorder(null);
        btnEnfermeiros.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btnEnfermeiros.setMinimumSize(new java.awt.Dimension(103, 17));
        btnEnfermeiros.setPreferredSize(new java.awt.Dimension(130, 35));
        btnEnfermeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnfermeirosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEnfermeiros, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(btnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnEnfermeiros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");

        menuSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        menuSalvar.setText("Salvar");
        menuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalvar);

        menuImportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/importar.png"))); // NOI18N
        menuImportar.setText("Importar");
        menuImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImportarActionPerformed(evt);
            }
        });
        jMenu1.add(menuImportar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        ListaConsultas c = new ListaConsultas(controlador);
        c.setResizable(false);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        // TODO add your handling code here:
        ListaPacientes listaPacientes = new ListaPacientes(controlador);
        listaPacientes.setResizable(false);
        listaPacientes.setLocationRelativeTo(null);
        listaPacientes.setVisible(true);
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void menuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarActionPerformed
//        // TODO add your handling code here:
        JFileChooser janelaArq = new JFileChooser();
        int retornoJan = janelaArq.showSaveDialog(this);

        if (retornoJan == JFileChooser.APPROVE_OPTION) {
            Object[] opcoes = {"Sim", "Não"};
            ImageIcon icon1 = new ImageIcon(HospitalController.class.getResource("../imagens/pergunta.png"));
            int confirma = JOptionPane.showOptionDialog(null, "Deseja salvar os dados em " + janelaArq.getSelectedFile().getName() + " ?", "Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, icon1, opcoes, opcoes[0]);
            if (confirma == 0) {
                controlador.salvar(janelaArq.getSelectedFile());
            }
        }
    }//GEN-LAST:event_menuSalvarActionPerformed

    private void menuImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImportarActionPerformed
        // TODO add your handling code here:
        JFileChooser janelaArq = new JFileChooser();
        int retornoJan = janelaArq.showOpenDialog(this);

        if (retornoJan == JFileChooser.APPROVE_OPTION) {
            controlador.importar(janelaArq.getSelectedFile());
        }
    }//GEN-LAST:event_menuImportarActionPerformed

    private void btnEnfermeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta1ActionPerformed
        // TODO add your handling code here:
        ListaEnfermeiros listaEnf = new ListaEnfermeiros(controlador);
        listaEnf.setLocationRelativeTo(null);
        listaEnf.setVisible(true);
    }//GEN-LAST:event_btnConsulta1ActionPerformed

    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
        // TODO add your handling code here:
        ListaMedicos listaMedicos = new ListaMedicos(controlador);
        listaMedicos.setLocationRelativeTo(null);
        listaMedicos.setVisible(true);
    }//GEN-LAST:event_btnMedicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Hospital h = new Hospital();
                h.setResizable(false);
                h.setLocationRelativeTo(null);
                h.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEnfermeiros;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuImportar;
    private javax.swing.JMenuItem menuSalvar;
    // End of variables declaration//GEN-END:variables
}
